### ISSUE TITLE
Can we open source DownloadingFileSystem ?

### ISSUE THREAD

**Issue by sockeqwe** [freeletics/mad#53]
I could need it for a side project 😉

Not sure if it belongs into this repo or is a library on its own (I would be happy to help make it KMP)

**Comment by sockeqwe** [comment]
Well I can also start over from scratch to cover my own simple use case (podcast app for android wear) and build it out via KMP more and more over time. The knowledge I have in my head about DownloadingFileSystem should be sufficient to start in an efficient way from scratch ...

**Comment by gabrielittner** [comment]
Closing this since I won't get to it in the foreseeable future
